// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *About Page Type → Artifacts*
 */
export interface AboutPageTypeDocumentDataInfluencesListItem {
  /**
   * Title field in *About Page Type → Artifacts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page_type.influences_list[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Credit field in *About Page Type → Artifacts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page_type.influences_list[].credit
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  credit: prismic.KeyTextField;

  /**
   * Cover Image field in *About Page Type → Artifacts*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page_type.influences_list[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Description field in *About Page Type → Artifacts*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page_type.influences_list[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Image Background field in *About Page Type → Artifacts*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page_type.influences_list[].image_background
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  image_background: prismic.ColorField;
}

type AboutPageTypeDocumentDataSlices3Slice = BodyCopySlice | OverlineSlice;

/**
 * Content for About Page Type documents
 */
interface AboutPageTypeDocumentData {
  /**
   * Page Title Overline field in *About Page Type*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page_type.page_title_overline
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  page_title_overline: prismic.KeyTextField;

  /**
   * Page Title field in *About Page Type*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page_type.page_title
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  page_title: prismic.KeyTextField;

  /**
   * TOC Overline field in *About Page Type*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page_type.toc_overline
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  toc_overline: prismic.KeyTextField;

  /**
   * Hero Image field in *About Page Type*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page_type.hero_image
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Overview field in *About Page Type*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page_type.overview
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  overview: prismic.RichTextField; /**
   * Meta Description field in *About Page Type*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about_page_type.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About Page Type*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page_type.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *About Page Type*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about_page_type.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField; /**
   * Section ID field in *About Page Type*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page_type.influences_section_id
   * - **Tab**: Influences
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  influences_section_id: prismic.KeyTextField;

  /**
   * Section Overline field in *About Page Type*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page_type.influences_section_overline
   * - **Tab**: Influences
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  influences_section_overline: prismic.KeyTextField;

  /**
   * Section Title field in *About Page Type*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page_type.influences_section_title
   * - **Tab**: Influences
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  influences_section_title: prismic.KeyTextField;

  /**
   * Artifacts field in *About Page Type*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page_type.influences_list[]
   * - **Tab**: Influences
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  influences_list: prismic.GroupField<
    Simplify<AboutPageTypeDocumentDataInfluencesListItem>
  >; /**
   * Outside of work section ID field in *About Page Type*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page_type.outside_of_work_section_id
   * - **Tab**: Outside of Work
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  outside_of_work_section_id: prismic.KeyTextField;

  /**
   * Slice Zone field in *About Page Type*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page_type.slices3[]
   * - **Tab**: Outside of Work
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices3: prismic.SliceZone<AboutPageTypeDocumentDataSlices3Slice>;
}

/**
 * About Page Type document from Prismic
 *
 * - **API ID**: `about_page_type`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutPageTypeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<AboutPageTypeDocumentData>,
    "about_page_type",
    Lang
  >;

/**
 * Item in *Articles Page Type → List*
 */
export interface ArticlesPageTypeDocumentDataListItem {
  /**
   * Overline field in *Articles Page Type → List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: articles_page_type.list[].overline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  overline: prismic.KeyTextField;

  /**
   * Title field in *Articles Page Type → List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: articles_page_type.list[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * URL field in *Articles Page Type → List*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: articles_page_type.list[].url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Description field in *Articles Page Type → List*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: articles_page_type.list[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * CTA Link Label field in *Articles Page Type → List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: articles_page_type.list[].cta_link_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_link_label: prismic.KeyTextField;
}

type ArticlesPageTypeDocumentDataSlicesSlice = never;

/**
 * Content for Articles Page Type documents
 */
interface ArticlesPageTypeDocumentData {
  /**
   * Page Title Overline field in *Articles Page Type*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: articles_page_type.page_title_overline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  page_title_overline: prismic.KeyTextField;

  /**
   * Title field in *Articles Page Type*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: articles_page_type.page_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  page_title: prismic.KeyTextField;

  /**
   * Overview field in *Articles Page Type*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: articles_page_type.page_overview
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  page_overview: prismic.RichTextField;

  /**
   * Hero Image field in *Articles Page Type*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: articles_page_type.hero_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * List field in *Articles Page Type*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: articles_page_type.list[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  list: prismic.GroupField<Simplify<ArticlesPageTypeDocumentDataListItem>>;

  /**
   * Slice Zone field in *Articles Page Type*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: articles_page_type.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ArticlesPageTypeDocumentDataSlicesSlice>; /**
   * Meta Description field in *Articles Page Type*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: articles_page_type.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Articles Page Type*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: articles_page_type.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Articles Page Type*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: articles_page_type.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Articles Page Type document from Prismic
 *
 * - **API ID**: `articles_page_type`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticlesPageTypeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArticlesPageTypeDocumentData>,
    "articles_page_type",
    Lang
  >;

type CaseStudyDocumentDataSlicesSlice =
  | VideoSlice
  | DeeperDetailsSlice
  | StoryOverviewSlice
  | QuoteSpreadSlice
  | SidebarSlice
  | OverlineSlice
  | BodyCopySlice
  | ImageSlice;

/**
 * Content for Case Study documents
 */
interface CaseStudyDocumentData {
  /**
   * Title field in *Case Study*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Project Name field in *Case Study*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.project_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  project_name: prismic.KeyTextField;

  /**
   * Case Study Type field in *Case Study*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.case_study_type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  case_study_type: prismic.KeyTextField;

  /**
   * Timeline field in *Case Study*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.timeline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  timeline: prismic.KeyTextField;

  /**
   * Project Image field in *Case Study*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.project_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  project_image: prismic.ImageField<never>;

  /**
   * Employer field in *Case Study*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.employer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  employer: prismic.KeyTextField;

  /**
   * Slice Zone field in *Case Study*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<CaseStudyDocumentDataSlicesSlice>; /**
   * Meta Description field in *Case Study*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: case_study.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Case Study*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Case Study*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: case_study.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Case Study document from Prismic
 *
 * - **API ID**: `case_study`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CaseStudyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CaseStudyDocumentData>,
    "case_study",
    Lang
  >;

type Ct1DocumentDataSlicesSlice = ImageSlice;

/**
 * Content for CT1 documents
 */
interface Ct1DocumentData {
  /**
   * Slice Zone field in *CT1*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: ct1.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<Ct1DocumentDataSlicesSlice>;
}

/**
 * CT1 document from Prismic
 *
 * - **API ID**: `ct1`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type Ct1Document<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<Ct1DocumentData>, "ct1", Lang>;

type Ct2DocumentDataSlicesSlice = BodyCopySlice;

/**
 * Content for CT2 documents
 */
interface Ct2DocumentData {
  /**
   * Slice Zone field in *CT2*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: ct2.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<Ct2DocumentDataSlicesSlice>;
}

/**
 * CT2 document from Prismic
 *
 * - **API ID**: `ct2`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type Ct2Document<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<Ct2DocumentData>, "ct2", Lang>;

type DeeperDetailsContentDocumentDataSlicesSlice = ImageSlice | BodyCopySlice;

/**
 * Content for Deeper Details Content documents
 */
interface DeeperDetailsContentDocumentData {
  /**
   * Slice Zone field in *Deeper Details Content*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: deeper_details_content.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<DeeperDetailsContentDocumentDataSlicesSlice>;
}

/**
 * Deeper Details Content document from Prismic
 *
 * - **API ID**: `deeper_details_content`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DeeperDetailsContentDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<DeeperDetailsContentDocumentData>,
    "deeper_details_content",
    Lang
  >;

/**
 * Item in *Homepage → Titles*
 */
export interface HomepageDocumentDataTitlesListItem {
  /**
   * Title field in *Homepage → Titles*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.titles_list[].title_item
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title_item: prismic.KeyTextField;
}

type HomepageDocumentDataSlicesSlice = CaseStudyTeaserSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Hero Intro field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.hero_intro
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_intro: prismic.RichTextField;

  /**
   * Hero Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.hero_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Case Study Heading field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.case_study_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  case_study_heading: prismic.RichTextField;

  /**
   * Additional Projects Heading field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.additional_projects_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  additional_projects_heading: prismic.RichTextField;

  /**
   * Titles field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.titles_list[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  titles_list: prismic.GroupField<Simplify<HomepageDocumentDataTitlesListItem>>;

  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>; /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Item in *Main Navigation → Links*
 */
export interface MainNavigationDocumentDataLinksItem {
  /**
   * Link field in *Main Navigation → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: main_navigation.links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Label field in *Main Navigation → Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: main_navigation.links[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;
}

/**
 * Content for Main Navigation documents
 */
interface MainNavigationDocumentData {
  /**
   * Links field in *Main Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: main_navigation.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  links: prismic.GroupField<Simplify<MainNavigationDocumentDataLinksItem>>;
}

/**
 * Main Navigation document from Prismic
 *
 * - **API ID**: `main_navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MainNavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MainNavigationDocumentData>,
    "main_navigation",
    Lang
  >;

type PageDocumentDataSlicesSlice = BodyCopySlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type StoryDocumentDataSlicesSlice = BodyCopySlice | ImageSlice | OverlineSlice;

/**
 * Content for Story documents
 */
interface StoryDocumentData {
  /**
   * Story Title field in *Story*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story.story_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  story_title: prismic.RichTextField;

  /**
   * Story Type field in *Story*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story.story_type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  story_type: prismic.KeyTextField;

  /**
   * Time Meta field in *Story*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story.time_meta
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  time_meta: prismic.KeyTextField;

  /**
   * Slice Zone field in *Story*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: story.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<StoryDocumentDataSlicesSlice>; /**
   * Meta Description field in *Story*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: story.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Story*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: story.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Story*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: story.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Story document from Prismic
 *
 * - **API ID**: `story`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type StoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<StoryDocumentData>, "story", Lang>;

export type AllDocumentTypes =
  | AboutPageTypeDocument
  | ArticlesPageTypeDocument
  | CaseStudyDocument
  | Ct1Document
  | Ct2Document
  | DeeperDetailsContentDocument
  | HomepageDocument
  | MainNavigationDocument
  | PageDocument
  | StoryDocument;

/**
 * Primary content in *BodyCopy → Default → Primary*
 */
export interface BodyCopySliceDefaultPrimary {
  /**
   * Content field in *BodyCopy → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: body_copy.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for BodyCopy Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BodyCopySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BodyCopySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BodyCopy*
 */
type BodyCopySliceVariation = BodyCopySliceDefault;

/**
 * BodyCopy Shared Slice
 *
 * - **API ID**: `body_copy`
 * - **Description**: BodyCopy
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BodyCopySlice = prismic.SharedSlice<
  "body_copy",
  BodyCopySliceVariation
>;

/**
 * Primary content in *CaseStudyTeaser → Default → Primary*
 */
export interface CaseStudyTeaserSliceDefaultPrimary {
  /**
   * Case Study Type field in *CaseStudyTeaser → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study_teaser.default.primary.case_study_type
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  case_study_type: prismic.KeyTextField;

  /**
   * Title field in *CaseStudyTeaser → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study_teaser.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Summary field in *CaseStudyTeaser → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study_teaser.default.primary.summary
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  summary: prismic.RichTextField;

  /**
   * Image field in *CaseStudyTeaser → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study_teaser.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * CMS Document field in *CaseStudyTeaser → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study_teaser.default.primary.cms_document
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  cms_document: prismic.ContentRelationshipField;

  /**
   * CTA Label field in *CaseStudyTeaser → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study_teaser.default.primary.cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_label: prismic.KeyTextField;
}

/**
 * Default variation for CaseStudyTeaser Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CaseStudyTeaserSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CaseStudyTeaserSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CaseStudyTeaser*
 */
type CaseStudyTeaserSliceVariation = CaseStudyTeaserSliceDefault;

/**
 * CaseStudyTeaser Shared Slice
 *
 * - **API ID**: `case_study_teaser`
 * - **Description**: CaseStudyTeaser
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CaseStudyTeaserSlice = prismic.SharedSlice<
  "case_study_teaser",
  CaseStudyTeaserSliceVariation
>;

/**
 * Primary content in *DeeperDetails → Default → Primary*
 */
export interface DeeperDetailsSliceDefaultPrimary {
  /**
   * Show Content Button Text field in *DeeperDetails → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: deeper_details.default.primary.show_content_button_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  show_content_button_text: prismic.RichTextField;

  /**
   * Body Copy field in *DeeperDetails → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: deeper_details.default.primary.body_copy
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body_copy: prismic.RichTextField;
}

/**
 * Default variation for DeeperDetails Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DeeperDetailsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DeeperDetailsSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *DeeperDetails → Freeform → Primary*
 */
export interface DeeperDetailsSliceImportedDocumentPrimary {
  /**
   * Show Content Button Text field in *DeeperDetails → Freeform → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: deeper_details.importedDocument.primary.show_content_button_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  show_content_button_text: prismic.RichTextField;

  /**
   * Document field in *DeeperDetails → Freeform → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: deeper_details.importedDocument.primary.document_relation
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  document_relation: prismic.ContentRelationshipField;
}

/**
 * Freeform variation for DeeperDetails Slice
 *
 * - **API ID**: `importedDocument`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DeeperDetailsSliceImportedDocument = prismic.SharedSliceVariation<
  "importedDocument",
  Simplify<DeeperDetailsSliceImportedDocumentPrimary>,
  never
>;

/**
 * Slice variation for *DeeperDetails*
 */
type DeeperDetailsSliceVariation =
  | DeeperDetailsSliceDefault
  | DeeperDetailsSliceImportedDocument;

/**
 * DeeperDetails Shared Slice
 *
 * - **API ID**: `deeper_details`
 * - **Description**: DeeperDetails
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DeeperDetailsSlice = prismic.SharedSlice<
  "deeper_details",
  DeeperDetailsSliceVariation
>;

/**
 * Primary content in *Image → Default → Primary*
 */
export interface ImageSliceDefaultPrimary {
  /**
   * Overline field in *Image → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image.default.primary.overline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  overline: prismic.KeyTextField;

  /**
   * Image field in *Image → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Caption field in *Image → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image.default.primary.caption
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  caption: prismic.RichTextField;

  /**
   * Image Style field in *Image → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: image.default.primary.image_style
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  image_style: prismic.SelectField<"Screenshot" | "Diagram">;

  /**
   * Display Size field in *Image → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: image.default.primary.display_size
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  display_size: prismic.SelectField<"Cover_Image" | "Large" | "Aside">;
}

/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation = ImageSliceDefault;

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageSlice = prismic.SharedSlice<"image", ImageSliceVariation>;

/**
 * Primary content in *NewChapter → Default → Primary*
 */
export interface OverlineSliceDefaultPrimary {
  /**
   * Overline field in *NewChapter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: overline.default.primary.overline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  overline: prismic.KeyTextField;

  /**
   * Chapter Title field in *NewChapter → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: overline.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Lede field in *NewChapter → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: overline.default.primary.lede
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  lede: prismic.RichTextField;
}

/**
 * Default variation for NewChapter Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OverlineSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OverlineSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NewChapter*
 */
type OverlineSliceVariation = OverlineSliceDefault;

/**
 * NewChapter Shared Slice
 *
 * - **API ID**: `overline`
 * - **Description**: Overline
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OverlineSlice = prismic.SharedSlice<
  "overline",
  OverlineSliceVariation
>;

/**
 * Primary content in *QuoteSpread → Default → Primary*
 */
export interface QuoteSpreadSliceDefaultPrimary {
  /**
   * Background Image field in *QuoteSpread → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: quote_spread.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Primary Content field in *QuoteSpread → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quote_spread.default.primary.primary_content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  primary_content: prismic.RichTextField;

  /**
   * Attribution field in *QuoteSpread → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quote_spread.default.primary.attribution
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  attribution: prismic.KeyTextField;

  /**
   * Supplemental Content field in *QuoteSpread → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quote_spread.default.primary.supplemental_content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  supplemental_content: prismic.RichTextField;
}

/**
 * Default variation for QuoteSpread Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type QuoteSpreadSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<QuoteSpreadSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *QuoteSpread*
 */
type QuoteSpreadSliceVariation = QuoteSpreadSliceDefault;

/**
 * QuoteSpread Shared Slice
 *
 * - **API ID**: `quote_spread`
 * - **Description**: QuoteSpread
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type QuoteSpreadSlice = prismic.SharedSlice<
  "quote_spread",
  QuoteSpreadSliceVariation
>;

/**
 * Primary content in *Sidebar → Items*
 */
export interface SidebarSliceDefaultItem {
  /**
   * Section Title field in *Sidebar → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sidebar.items[].section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Content field in *Sidebar → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sidebar.items[].content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for Sidebar Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SidebarSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<SidebarSliceDefaultItem>
>;

/**
 * Slice variation for *Sidebar*
 */
type SidebarSliceVariation = SidebarSliceDefault;

/**
 * Sidebar Shared Slice
 *
 * - **API ID**: `sidebar`
 * - **Description**: Sidebar
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SidebarSlice = prismic.SharedSlice<
  "sidebar",
  SidebarSliceVariation
>;

/**
 * Primary content in *StoryOverview → Default → Primary*
 */
export interface StoryOverviewSliceDefaultPrimary {
  /**
   * Body Copy field in *StoryOverview → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_overview.default.primary.body_copy
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body_copy: prismic.RichTextField;
}

/**
 * Primary content in *StoryOverview → Items*
 */
export interface StoryOverviewSliceDefaultItem {
  /**
   * Section Title field in *StoryOverview → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_overview.items[].section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Section Content field in *StoryOverview → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_overview.items[].section_content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_content: prismic.RichTextField;
}

/**
 * Default variation for StoryOverview Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StoryOverviewSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StoryOverviewSliceDefaultPrimary>,
  Simplify<StoryOverviewSliceDefaultItem>
>;

/**
 * Slice variation for *StoryOverview*
 */
type StoryOverviewSliceVariation = StoryOverviewSliceDefault;

/**
 * StoryOverview Shared Slice
 *
 * - **API ID**: `story_overview`
 * - **Description**: StoryOverview
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StoryOverviewSlice = prismic.SharedSlice<
  "story_overview",
  StoryOverviewSliceVariation
>;

/**
 * Primary content in *VimeoClip → Default → Primary*
 */
export interface VideoSliceDefaultPrimary {
  /**
   * Overline field in *VimeoClip → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video.default.primary.overline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  overline: prismic.KeyTextField;

  /**
   * Vimeo ID field in *VimeoClip → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video.default.primary.vimeo_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  vimeo_id: prismic.KeyTextField;

  /**
   * Caption field in *VimeoClip → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video.default.primary.caption
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  caption: prismic.RichTextField;
}

/**
 * Default variation for VimeoClip Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VimeoClip*
 */
type VideoSliceVariation = VideoSliceDefault;

/**
 * VimeoClip Shared Slice
 *
 * - **API ID**: `video`
 * - **Description**: Video
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoSlice = prismic.SharedSlice<"video", VideoSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutPageTypeDocument,
      AboutPageTypeDocumentData,
      AboutPageTypeDocumentDataInfluencesListItem,
      AboutPageTypeDocumentDataSlices3Slice,
      ArticlesPageTypeDocument,
      ArticlesPageTypeDocumentData,
      ArticlesPageTypeDocumentDataListItem,
      ArticlesPageTypeDocumentDataSlicesSlice,
      CaseStudyDocument,
      CaseStudyDocumentData,
      CaseStudyDocumentDataSlicesSlice,
      Ct1Document,
      Ct1DocumentData,
      Ct1DocumentDataSlicesSlice,
      Ct2Document,
      Ct2DocumentData,
      Ct2DocumentDataSlicesSlice,
      DeeperDetailsContentDocument,
      DeeperDetailsContentDocumentData,
      DeeperDetailsContentDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataTitlesListItem,
      HomepageDocumentDataSlicesSlice,
      MainNavigationDocument,
      MainNavigationDocumentData,
      MainNavigationDocumentDataLinksItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      StoryDocument,
      StoryDocumentData,
      StoryDocumentDataSlicesSlice,
      AllDocumentTypes,
      BodyCopySlice,
      BodyCopySliceDefaultPrimary,
      BodyCopySliceVariation,
      BodyCopySliceDefault,
      CaseStudyTeaserSlice,
      CaseStudyTeaserSliceDefaultPrimary,
      CaseStudyTeaserSliceVariation,
      CaseStudyTeaserSliceDefault,
      DeeperDetailsSlice,
      DeeperDetailsSliceDefaultPrimary,
      DeeperDetailsSliceImportedDocumentPrimary,
      DeeperDetailsSliceVariation,
      DeeperDetailsSliceDefault,
      DeeperDetailsSliceImportedDocument,
      ImageSlice,
      ImageSliceDefaultPrimary,
      ImageSliceVariation,
      ImageSliceDefault,
      OverlineSlice,
      OverlineSliceDefaultPrimary,
      OverlineSliceVariation,
      OverlineSliceDefault,
      QuoteSpreadSlice,
      QuoteSpreadSliceDefaultPrimary,
      QuoteSpreadSliceVariation,
      QuoteSpreadSliceDefault,
      SidebarSlice,
      SidebarSliceDefaultItem,
      SidebarSliceVariation,
      SidebarSliceDefault,
      StoryOverviewSlice,
      StoryOverviewSliceDefaultPrimary,
      StoryOverviewSliceDefaultItem,
      StoryOverviewSliceVariation,
      StoryOverviewSliceDefault,
      VideoSlice,
      VideoSliceDefaultPrimary,
      VideoSliceVariation,
      VideoSliceDefault,
    };
  }
}
